print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()
print(f"So, you're {age} years old, {height} tall and {weight} heavy.")

age = input("How old are you? ")
height = input("How tall are you? ")
weight = input("How much do you weigh? ")
friend_name = input("What is the name of your friend? ")
print(f"So, you're {age} old, {height} tall and {weight} heavy. Your friend is called {friend_name}")